### ISSUE TITLE
Unable to push to Github during release

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#1396]
I encountered a similar error a few weeks ago, and the fix was to force the Gitlab check status to be success using the `github_status_check.py` script. I don't think that fix will apply here however, because the status check that is failing is from Travis.

@hannes-ucsc  can you take a look?

```
(.venv) jesse@vader ~/gi/azul.stable (prod)$ git push origin 
Counting objects: 6, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (6/6), 674 bytes | 224.00 KiB/s, done.
Total 6 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/prod.
remote: error: Required status check "continuous-integration/travis-ci" is expected.
To github.com:DataBiosphere/azul.git
 ! [remote rejected]   prod -> prod (protected branch hook declined)
error: failed to push some refs to 'git@github.com:DataBiosphere/azul.git'
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-849)
┆Project Name: azul
┆Issue Number: AZUL-849

**Comment by jessebrennan** [comment]
More information:

@hannes-ucsc claimed it's impossible for `gitlab.dev/staging` to be ahead of `origin/staging` and for the build to pass presumably because
```
$ python scripts/github_status_check.py pending
```
would fail.

This claim is not true.
```
(.venv) jesse@vader ~/gi/azul.stable (staging)$ git log
commit c5d6b776f8b24809f5a1d959a0bf084b33744bd1 (HEAD -> staging, gitlab.dev/staging)
Merge: 207f1963 2a5dd14e
Author: jessebrennan <brennan@ucsc.edu>
Date:   Wed Oct 9 08:10:10 2019 -0700

    Merge branch 'integration' into staging

commit 207f19636b088ae1edd5ccc3f8ae9d6aa226a449 (origin/staging)
Merge: 5b0a3a79 b974316f
Author: jessebrennan <brennan@ucsc.edu>
Date:   Tue Oct 8 17:04:57 2019 -0700

    Fix: DSS staging bucket swap (PR #1331)
```
and https://gitlab.dev.explore.data.humancellatlas.org/azul/azul/-/jobs/4113 should be sufficient proof (notice that the commit hashes match between the Gitlab build and the log).

When I try to push to origin, I get
```
(.venv) jesse@vader ~/gi/azul.stable (staging)$ git push origin
Total 0 (delta 0), reused 0 (delta 0)
remote: error: GH006: Protected branch update failed for refs/heads/staging.
remote: error: Required status check "continuous-integration/travis-ci" is expected.
To github.com:DataBiosphere/azul.git
 ! [remote rejected]   staging -> staging (protected branch hook declined)
error: failed to push some refs to 'git@github.com:DataBiosphere/azul.git'
```

**Comment by jessebrennan** [comment]
Looking at Github, the current Travis build is passing on staging. I'm confused as to why then, I should be prohibited from pushing to staging.

The only alternative I can think of is that Github expects Travis to have run on this specific commit that I am going to be pushing. The only way to achieve this before hand is to have made a PR. That's not the procedure we want.

I think that the only status check we want to be blocking for merges on `staging`, `integration`, and `prod` is the Gitlab check. Otherwise a PR will have to be made any time anyone is doing a deployment. This wasn't the procedure before, and I'm not sure how this reversion happened. @hannes-ucsc can you remove this status check requirement and or confirm my suspicion?

**Comment by hannes-ucsc** [comment]
I'm going to take a look. A few observations:

1) I'm not making the github_status_check failure up. It did happen: https://gitlab.dev.explore.data.humancellatlas.org/azul/azul/-/jobs/3933

2) The `git log` output only proves where your tracking branches are, not where the actual remote branches are.

**Comment by hannes-ucsc** [comment]
When we post `git push` error messages we should include what commit we we're trying to push.

**Comment by hannes-ucsc** [comment]
> I think that the only status check we want to be blocking for merges on staging, integration, and prod is the Gitlab check. Otherwise a PR will have to be made any time anyone is doing a deployment.

Not true. Status checks cover both PRs and normal pushes of merge commits.

> This wasn't the procedure before, and I'm not sure how this reversion happened. 

There was no reversion. We've always had the Travis and Gitlab status checks for the integration, staging and prod branches enabled. The only changes we've made were whether we include coverage as a status check (which we now don't because both coverage providers are slow/flaky) and `develop` does not require the Gitlab check because I don't want to force all PRs through the sandbox.

Check this out:

```
$ git ls-remote gitlab.dev | grep c5d6b776
c5d6b776f8b24809f5a1d959a0bf084b33744bd1	refs/heads/staging
$ git ls-remote origin | grep c5d6b776
c5d6b776f8b24809f5a1d959a0bf084b33744bd1	refs/tags/deployed/staging/2019-10-29__17-47
```

You must have pushed the tag do Github which makes the commit known to Github and therefore lets the Gitlab build publish a build status for that commit. However, the origin staging branch is still lagging:

```
$ git ls-remote origin staging
207f19636b088ae1edd5ccc3f8ae9d6aa226a449	refs/heads/staging
```

Now when you are merging c5d6b776f8b24809f5a1d959a0bf084b33744bd1 from your local staging (which is ahead of origin/staging) into prod, and then push that merge commit to Github, Github rightfully complains because while there is a successful build status for c5d6b776f8b24809f5a1d959a0bf084b33744bd1 that commit is not on the source branch of the merge until you push your staging branch to Gitlab. Do the push and then wait for the resulting Travis build to succeed. Then push the prod branch again.

**Comment by hannes-ucsc** [comment]
Note that you are not supposed to push the deployment tag until after the GL build of the promotion merge succeeds.

**Comment by jessebrennan** [comment]
> You must have pushed the tag do Github which makes the commit known to Github and therefore lets the Gitlab build publish a build status for that commit

This is not true. I pushed the tag only today, because I realized I hadn't done it before. The tag is `deployed/staging/2019-10-29__17-47`. Sorry that my changes are making this more confusing.

> Note that you are not supposed to push the deployment tag until after the GL build of the promotion merge succeeds.

I am aware, and did not stray from this procedure.

> Do the push and then wait for the resulting Travis build to succeed. Then push the prod branch again.

I stated in an earlier message that I was unable to push to staging. To my surprise, when I just tried it again it succeeded. I'm unsure what was different. Sorry for the confusion. Your explanation makes a lot of sense. I (clearly) didn't understand how the status checks worked for merges.

> When we post git push error messages we should include what commit we we're trying to push.

I agree. My bash prompt includes the branch I was on at the time and I thought this was sufficient, but again, I was wrong.

Thanks for taking a deeper look at this.

**Comment by jessebrennan** [comment]
@hannes-ucsc and I were unable to recreate this. We will keep monitoring this issue to see if it occurs again.

Another suspicious (but not conclusive) detail was the fact that there was a hotfix in staging which was not in develop nor integration. There is a setting for status checks that require the source branch to be up to date. This setting is activated for integration, staging, and prod (but not dev). This seems to imply that merging should have failed. Yet eventually, it did pass, without a clear indication of anything changing.

If Github was treating the commit as a fast-forward merge, it's behaviour would have made sense. Perhaps if the setting described above didn't apply for fast-forward merges, the current behaviour could be explained?

**Comment by jessebrennan** [comment]
@hannes-ucsc this is happening again, but on the prod deploy. It looks to me like there is a hotfix on prod that was not backported to staging. That could be the culprit.

First I checked the latest prod and the latest staging branches for their status checks. Staging had all of the expected status checks, but prod https://github.com/DataBiosphere/azul/commit/59b5989f78c08f52ef0f68b0f5bda6c27db92fa6 was missing the Gitlab status check, so I added it manually. That didn't change anything. The log was still
```
(.venv) jesse@vader ~/gi/azul.stable (prod)$ git push origin 
Counting objects: 4, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (4/4), 418 bytes | 139.00 KiB/s, done.
Total 4 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/prod.
remote: error: 2 of 2 required status checks have not succeeded: 1 expected and 1 pending.
To github.com:DataBiosphere/azul.git
 ! [remote rejected]   prod -> prod (protected branch hook declined)
error: failed to push some refs to 'git@github.com:DataBiosphere/azul.git'
```

**Comment by hannes-ucsc** [comment]
> It looks to me like there is a hotfix on prod that was not backported to staging. That could be the culprit.

We usually just backport to `develop` and that was done for this change, too.

> Staging had all of the expected status checks, but prod 59b5989 was missing the Gitlab status check, so I added it manually. That didn't change anything.

Unsurprisingly so. I thought we had already confirmed that the target branch is not considered when pushing a merge. Only the tip of the source branch.

I wonder how is it possible that GL was able to publish a status for the merge commit if you had never successfully pushed that commit to GH. 

The only thing that was special today is that GH prod was ahead of GL prod by one commit. But the same thing has happened to you when the target branch of a promotion was consistent between GL and GH. I want you to consider the possibility that this is specific to your setup or something you do differently to the other two REs. Neither of them has had this problem recently.

**Comment by hannes-ucsc** [comment]
After I disabled _Require branches to be up to date before merging_ @jessebrennan was able to push.

![image](https://user-images.githubusercontent.com/5143256/70077724-3a072780-15b6-11ea-9184-bc9261e540e9.png)

This is inconsistent with previous occasions where the source branch was up to date and @jessebrennan was still not able to push but a few hours later was able to without any configuration changes. However, I am going to ignore that and close this issue since today @jessebrennan was not able to push before I disabled the box and immediately afterwards was able to.

**Comment by jessebrennan** [comment]
>  I want you to consider the possibility that this is specific to your setup or something you do differently to the other two REs. Neither of them has had this problem recently.

@achave11 tested this for me and ran into the same issue.
