### ISSUE TITLE
IT subtests `manifest` and `repository_files` fail due to lack of files

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5168]
https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/2673

```
======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [manifest] (catalog='anvil-it', format=None)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 378, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 559, in _test_manifest
    validator(catalog, response)
  File "/builds/ucsc/azul/test/integration_test.py", line 684, in _check_manifest
    self.__check_manifest(BytesIO(response), 'bundle_uuid')
  File "/builds/ucsc/azul/test/integration_test.py", line 760, in __check_manifest
    self.assertGreater(len(rows), 0)
AssertionError: 0 not greater than 0
======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [manifest] (catalog='anvil-it', format=<ManifestFormat.compact: 'compact'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 378, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 559, in _test_manifest
    validator(catalog, response)
  File "/builds/ucsc/azul/test/integration_test.py", line 684, in _check_manifest
    self.__check_manifest(BytesIO(response), 'bundle_uuid')
  File "/builds/ucsc/azul/test/integration_test.py", line 760, in __check_manifest
    self.assertGreater(len(rows), 0)
AssertionError: 0 not greater than 0
======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [repository_files] (catalog='anvil-it')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 378, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 788, in _test_repository_files
    file = self._get_one_file(catalog)
  File "/builds/ucsc/azul/test/integration_test.py", line 581, in _get_one_file
    self.fail('No files found')
AssertionError: No files found
```

There seem to be many bundles without any files in the 1000G snapshot, so the integration subtests that rely on presence of files in the index fail frequently, depending on the random seed chosen.

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
This needs 

- better reproduction (a seed where the tests fail), 
- symptoms and 
- verification of the hypothesized cause (many bundles without files in 1000G).

Spike for these, but assignee will need access to `anvilprod`.

**Comment by achave11-ucsc** [comment]
@hannes-ucsc": "Alternatively, assignee could index the three snapshots from `anvilprod` in a personal deployment."

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Lets hand over the spike to @nadove-ucsc, who will need to ask for the following permissions:
- developer on anvilprod via email to Erich
- access to anvil snapshots in TDR dev via Slack post to @hannes-ucsc"

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "#5207 might reduce the prevalence of this problem because it would add supplementary files in `anvilprod` from the 1000G snapshot."

**Comment by dsotirho-ucsc** [comment]
Hold off on spike until blocker has been reviewed.

**Comment by nadove-ucsc** [comment]
Now that we index supplementary files, and #5207 and #5229 have been resolved, @hannes-ucsc will test without a pinned seed and with the failing seed.

**Comment by hannes-ucsc** [comment]
IT passed with unpinned seed: https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/4927

**Comment by hannes-ucsc** [comment]
Failed with seed pinned to the one from the build the description links to: 

https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/4939

```diff
Subject: [PATCH] Attempt to reproduce #5168 with failing seed
---
Index: test/integration_test.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/integration_test.py b/test/integration_test.py
--- a/test/integration_test.py	(revision 6f9314cfa76593d6545e7c1fd283312818a78aca)
+++ b/test/integration_test.py	(revision 6dba204631d7e4f6c505c054e4a938d8c03650ba)
@@ -198,7 +198,11 @@
         super().setUp()
         # All random operations should be made using this seed so that test
         # results are deterministically reproducible
-        self.random_seed = randint(0, sys.maxsize)
+        self.random_seed = (
+            4499314249655548603
+            if config.deployment_stage == 'anvilprod' else
+            randint(0, sys.maxsize)
+        )
         self.random = Random(self.random_seed)
         log.info('Using random seed %r', self.random_seed)
 
```

**Comment by hannes-ucsc** [comment]
So it appears there is still a problem. I will reintroduce to my branch  the commit that pins a known working seed. I'd like the assignee to 1) reproduce in a personal deployment, 2) confirm that the hypothesis is correct (no files in bundles selected for indexing in that seed) and 3) attempt to propose a solution but I am happy to wait with all that until the last remaining blocker (#5015) lands.

**Comment by nadove-ucsc** [comment]
> I'd like the assignee to ... reproduce in a personal deployment,

Reproduced on personal deployment after applying the following changes:

```diff
Subject: [PATCH] fix
---
Index: test/integration_test.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/integration_test.py b/test/integration_test.py
--- a/test/integration_test.py	(revision 20ab20878aa86be5a2b80f521da4e3063d0fce8c)
+++ b/test/integration_test.py	(date 1686218296146)
@@ -203,7 +203,8 @@
             #        https://github.com/DataBiosphere/azul/issues/5168
             6634795309975096822
             if config.deployment_stage == 'anvilprod' else
-            randint(0, sys.maxsize)
+            # Pinned to reproduce failure from https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/2673
+            4499314249655548603
         )
         self.random = Random(self.random_seed)
         log.info('Using random seed %r', self.random_seed)
@@ -270,7 +271,7 @@
         fqids = self.azul_client.list_bundles(catalog, source, partition_prefix)
         bundle_count = len(fqids)
         partition = f'Partition {effective_prefix!r} of source {source.spec}'
-        if not config.is_sandbox_or_personal_deployment:
+        if True:
             # For sources that use partitioning, 512 is the desired partition
             # size. In practice, we observe the reindex succeeding with sizes
             # >700 without the partition size becoming a limiting factor. From
@@ -430,7 +431,7 @@
         # test once. Then also set `index` to False. Subsequent runs will use
         # catalogs from first run. Don't commit changes to these two lines.
         index = True
-        delete = True
+        delete = False
 
         if index:
             self._reset_indexer()
Index: src/azul/terra.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/terra.py b/src/azul/terra.py
--- a/src/azul/terra.py	(revision 20ab20878aa86be5a2b80f521da4e3063d0fce8c)
+++ b/src/azul/terra.py	(date 1686217915820)
@@ -647,7 +647,7 @@
                     # FIXME: AnVIL deployments conflate indexer and public SAs
                     #        https://github.com/DataBiosphere/azul/issues/4398
                     config.ServiceAccount.indexer
-                    if config.aws_account_name == 'platform-anvil-dev' else
+                    if False else
                     config.ServiceAccount.public
                 )
             )
```

**Comment by nadove-ucsc** [comment]
> ... confirm that the hypothesis is correct (no files in bundles selected for indexing in that seed) 

While no _public_ files are indexed with that seed, there _are_ managed access files.

```
$ curl -s -X GET 'https://service.nadove5.anvil.gi.ucsc.edu/index/files?catalog=anvilprodtest-it' | jq .pagination.total
0
$ curl -s -X GET 'https://service.nadove5.anvil.gi.ucsc.edu/index/files?catalog=anvilprodtest-it&size=100' -H "Authorization: Bearer $(gcloud auth print-access-token)" | jq .pagination.total
78
$ curl -s -X GET 'https://service.nadove5.anvil.gi.ucsc.edu/index/files?catalog=anvilprodtest-it&size=100' -H "Authorization: Bearer $(gcloud auth print-access-token)" | jq -r .hits[].sources[].sourceSpec | sort | uniq -c
     28 tdr:datarepo-dev-42c70e6a:snapshot/ANVIL_CCDG_Sample_1_20230228_ANV5_202302281520:/0
     50 tdr:datarepo-dev-97ad270b:snapshot/ANVIL_CMG_Sample_1_20230225_ANV5_202302281509:/0
```

I'm a bit confused by this because none of the source in `environment.py` for `anvilprod` as marked as managed access, but based on my experiments it appears that 1000 genomes is public and the other two are not.

**Comment by nadove-ucsc** [comment]
> ... attempt to propose a solution

The IT is supposed to always index bundles from at least one public source, but it appears this mechanism is currently broken due to this line: https://github.com/DataBiosphere/azul/blob/20ab20878aa86be5a2b80f521da4e3063d0fce8c/test/integration_test.py#L332

Due to a type mismatch (source spec vs. source ref), the check to detect whether a source is public or not always returns true, and thus fails to ensure that a public source is in fact indexed.

With this change applied on top of the previous one, the tests pass:

```diff
Subject: [PATCH] fix
---
Index: test/integration_test.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/integration_test.py b/test/integration_test.py
--- a/test/integration_test.py	(revision a4e5f0ef7c8716476baed4eac92f64a7e8e9aef6)
+++ b/test/integration_test.py	(date 1686221699252)
@@ -326,7 +326,8 @@
         self.random.shuffle(sources)
         if public_1st:
             managed_access_sources = frozenset(
-                map(str, self.managed_access_sources_by_catalog[catalog])
+                str(source.spec)
+                for source in self.managed_access_sources_by_catalog[catalog]
             )
             index = first(
                 i for i, source in enumerate(sources)
```

**Comment by dsotirho-ucsc** [comment]
Assignee to review Noa's findings.

**Comment by hannes-ucsc** [comment]
```diff
Index: test/integration_test.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/integration_test.py b/test/integration_test.py
--- a/test/integration_test.py	(revision bd1bd60a772fa1f8db9dd76c72831b4c6cdda085)
+++ b/test/integration_test.py	(date 1686271967823)
@@ -325,10 +325,12 @@
         self.random.shuffle(sources)
         if public_1st:
             managed_access_sources = frozenset(
-                map(str, self.managed_access_sources_by_catalog[catalog])
+                str(source.spec)
+                for source in self.managed_access_sources_by_catalog[catalog]
             )
             index = first(
-                i for i, source in enumerate(sources)
+                i 
+                for i, source in enumerate(sources)
                 if source not in managed_access_sources
             )
             sources[0], sources[index] = sources[index], sources[0]
```

But, yes, let's more forward with this fix.

**Comment by dsotirho-ucsc** [comment]
After being merged to `develop` PR https://github.com/DataBiosphere/azul/pull/5305 failed IT on `anvilprod`. IT was successful on both `dev` and `anvildev` however.

The [1st attempt](https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/5837) failed during `_assert_catalog_complete`
```
======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [catalog_complete] (catalog='anvil-it')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 386, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 1031, in _assert_catalog_complete
    self.assertSetEqual(indexed_fqids, expected_fqids)
AssertionError: Items in the first set but not the second:
AnvilBundleFQID(uuid='2e25fa2f-8c74-a7fe-be19-a6079ea32572', version='2022-06-01T00:00:00.000000Z', source=SourceRef(id='cc1c98a4-bfc4-45f2-b8dc-e920e5ca634d', spec=TDRSourceSpec(prefix=Prefix(common='', partition=2), project='datarepo-dev-43738c90', name='ANVIL_1000G_2019_Dev_20230302_ANV5_202303032342', is_snapshot=True)), entity_type=<BundleEntityType.primary: 'biosample'>)
Items in the second set but not the first:
AnvilBundleFQID(uuid='2e25fa2f-8c74-a7fe-be19-a6079ea32572', version='2022-06-01T00:00:00.000000Z', source=SourceRef(id='cc1c98a4-bfc4-45f2-b8dc-e920e5ca634d', spec=TDRSourceSpec(prefix=Prefix(common='', partition=2), project='datarepo-dev-43738c90', name='ANVIL_1000G_2019_Dev_20230302_ANV5_202303032342', is_snapshot=True)), entity_type=<BundleEntityType.supplementary: 'file'>)
```

Attempts [#2 to #5 ](https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/5841) failed during `assert_manifest`
```
======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [managed_access_manifest]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 386, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 1111, in _test_managed_access
    self._test_managed_access_manifest(catalog,
  File "/builds/ucsc/azul/test/integration_test.py", line 1280, in _test_managed_access_manifest
    assert_manifest({public_bundle, *managed_access_bundles})
  File "/builds/ucsc/azul/test/integration_test.py", line 1275, in assert_manifest
    self.assertEqual(expected_bundles, all_found_bundles)
AssertionError: Items in the first set but not the second:
'291afe95-9dad-a52d-bcdb-85d23f878057'
```

**Comment by achave11-ucsc** [comment]
This happened again during `anvilbox` IT run. https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/18689#L1044
